name: Feature request
description: Suggest an idea
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options: [nice to have, important, critical]
