name: nightly-prop

on:
  schedule:
    - cron: "17 2 * * *"
  workflow_dispatch: {}

jobs:
  property-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - run: python -m pip install -U pip
      - run: python -m pip install -e ".[dev]"
      - name: Run property tests (nightly profile)
        env:
          HYPOTHESIS_PROFILE: nightly
        run: pytest -q -m "prop"
