name: publish

on:
  workflow_dispatch:
    inputs:
      target:
        description: "Where to publish"
        type: choice
        options: ["pypi", "testpypi"]
        default: "pypi"
      ref:
        description: "Git ref to publish (tag or branch). Leave blank to use default branch."
        required: false
        default: ""

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.inputs.ref || '' }}

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install build tools
        run: |
          python -m pip install -U pip
          python -m pip install -U build twine

      - name: Build sdist and wheel
        run: python -m build

      - name: Publish to TestPyPI
        if: ${{ inputs.target == 'testpypi' }}
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: |
          python -m twine upload --repository-url https://test.pypi.org/legacy/ --non-interactive dist/*

      - name: Publish to PyPI
        if: ${{ inputs.target == 'pypi' }}
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m twine upload --non-interactive dist/*
