name: release

on:
  push:
    tags:
      - "v*"

jobs:
  build-attach:
    name: Build package, test, attach to GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write   # to create GitHub Release & upload assets
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install build & dev deps
        run: |
          python -m pip install -U pip
          python -m pip install -U build
          python -m pip install -e ".[dev]"

      - name: Run tests
        run: pytest -q

      - name: Build sdist and wheel
        run: python -m build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

      - name: Create/Update GitHub Release with artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          draft: false
          prerelease: ${{ contains(github.ref_name, '-rc') || contains(github.ref_name, 'alpha') || contains(github.ref_name, 'beta') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-matrix:
    name: Test (3.10–3.12)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install package (dev)
        run: |
          python -m pip install -U pip
          python -m pip install -e ".[dev]"
      - name: Run tests
        run: pytest -q
